TC001_VERIFY_LOGIN:
  name: TC001 Verify Login
  type: pytest
  path: python_playwright/tests/test_tc001_verify_login.py
  enabled: true
TC002_RESET_PASSWORD:
  name: TC002 Reset Password
  type: pytest
  path: python_playwright/tests/test_tc002_reset_password.py
  enabled: true
TC003_VERIFY_LOGIN_ERROR_MESSAGE:
  name: TC003 Verify Login Error Message
  type: pytest
  path: python_playwright/tests/test_tc003_verify_login_error_message.py
  enabled: true
TC004_VERIFY_INFO_AND_RESOURCE:
  name: TC004 Verify Info and Resource
  type: pytest
  path: python_playwright/tests/test_tc004_verify_info_and_resource.py
  enabled: true
TC005_VERIFY_MY_ACCOUNT_PAGES:
  name: TC005 Verify My Account Pages
  type: pytest
  path: python_playwright/tests/test_tc005_verify_my_account_pages.py
  enabled: true
TC006_SEARCH_FUNCTIONALITY:
  name: TC006 Search Functionality
  type: pytest
  path: python_playwright/tests/test_tc006_search_functionality.py
  enabled: true
TC007_CATEGORY_NAVIGATION:
  name: TC007 Category Navigation Functionality
  type: pytest
  path: python_playwright/tests/test_tc007_category_navigation_functionality.py
  enabled: true
TC008_FACET_NAVIGATION:
  name: TC008 Facet Navigation
  type: pytest
  path: python_playwright/tests/test_tc008_facet_navigation.py
  enabled: true
TC010_FREESTYLE_HEADWEAR_PAGE:
  name: TC010 Freestyle Headwear Page
  type: pytest
  path: python_playwright/tests/test_tc010_freestyle_headwear_page.py
  enabled: true
TC011_FREESTYLE_DIGITAL_PRINT:
  name: TC011 Freestyle Digital Print
  type: pytest
  path: python_playwright/tests/test_tc011_freestyle_digital_print.py
  enabled: true
TC012_FREESTYLE_SUBLIMATION_PAGE:
  name: TC012 Freestyle Sublimation Page
  type: pytest
  path: python_playwright/tests/test_tc012_freestyle_sublimation_page.py
  enabled: true
TC013_HOME_PAGE_VALIDATION:
  name: TC013 Home Page Validation
  type: pytest
  path: python_playwright/tests/test_tc013_home_page_validation.py
  enabled: true
TC014_BLANK_PLP_VALIDATION:
  name: TC014 Blank PLP Validation
  type: pytest
  path: python_playwright/tests/test_tc014_blank_plp_validation.py
  enabled: true
TC015_BLANK_PDP_VALIDATION:
  name: TC015 Blank PDP Validation
  type: pytest
  path: python_playwright/tests/test_tc015_blank_pdp_validation.py
  enabled: true
TC016_BLANK_ORDER_FEDEX_2DAY_AM:
  name: TC016 Blank Order With FedEx 2Day AM
  type: pytest
  path: python_playwright/tests/test_tc016_blank_order_with_fedex_2day_am.py
  enabled: true
TC017_SHIPPING_FEDEX_GROUND:
  name: TC017 Verify Shipping FedEx Ground
  type: pytest
  path: python_playwright/tests/test_tc017_verify_shipping_fedex_ground_validation.py
  enabled: true
TC018_SHIPPING_FEDEX_2DAY:
  name: TC018 Verify Shipping FedEx 2Day
  type: pytest
  path: python_playwright/tests/test_tc018_verify_shipping_fedex_2day_validation.py
  enabled: true
TC019_BLANK_ORDER_FEDEX_2DAY:
  name: TC019 Blank Order With FedEx 2Day
  type: pytest
  path: python_playwright/tests/test_tc019_blank_order_with_fedex_2day.py
  enabled: true
TC020_VERIFY_BLANK_ORDER:
  name: TC020 Verify Blank Order
  type: pytest
  path: python_playwright/tests/test_tc020_verify_blank_order.py
  enabled: true
TC021_SUBLIMATION_ORDER:
  name: TC021 Sublimation Order Placing
  type: pytest
  path: python_playwright/tests/test_tc021_sublimation_order_placing.py
  enabled: true
TC022_BLANK_ORDER_FEDEX_NEXT_DAY_AM:
  name: TC022 Blank Order With FedEx Next Day AM
  type: pytest
  path: python_playwright/tests/test_tc022_blank_order_with_fedex_next_day_am.py
  enabled: true
TC023_SUBLIMATION_ORDER_2:
  name: TC023 Sublimation Order Placing
  type: pytest
  path: python_playwright/tests/test_tc023_sublimation_order_placing.py
  enabled: true
